#  ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://midl.dev
baseurl: ""
title: MIDL.dev - Sui Validator
logo: MIDLLOGO.png
email: hello@midl.dev
author: MIDL team
description: > # "Write an awesome description for your new site here. 
  MIDL.dev provides Sui validation services. Delegate your Sui to MIDL.dev today for low commission and high reliability.
copyright: 'Copyright &copy; 2024 MIDL.DEV. All Rights Reserved.'
company: 'MIDLDEV OÜ (registry code: 14973249 | registration number EE102369869) | Kentmanni tn 9-43, Tallinn 10116, Estonia'
favicon: "./favicon.ico" # set the favicon of the site
permalink: pretty

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

exclude:
- bundle
- _cryptocurrencies
- _frontpage_items
- _frontpage_lower_items
- _operations
- _services
- _posts
